name: Smoke Test (after Deploy)
on: { workflow_dispatch: {} }
jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
      ENDPOINTS: ${{ secrets.SMOKE_ENDPOINTS }}
      DEFAULT_ENDPOINTS: "/api/_audit/diag /api/health /api/portfolio/properties?limit=1"
    steps:
      - name: Resolve base URL
        run: |
          if [ -z "${APP_BASE_URL:-}" ]; then
            echo "::error::Missing APP_BASE_URL secret"; exit 1
          fi
          echo "Using $APP_BASE_URL"
      - name: Run smoke
        run: |
          set -e
          base="${APP_BASE_URL%/}"
          eps="${ENDPOINTS:-$DEFAULT_ENDPOINTS}"
          echo "Base: $base"
          echo "Endpoints: $eps"
          ok=0; failures=()
          for p in $eps; do
            url="$base$p"
            echo "GET $url"
            code=$(curl -s -o /dev/null -w "%{http_code}" "$url" || echo 000)
            case "$code" in
              2??|401|403) echo "OK ($code) $p"; ok=1; break ;;
              *) echo "FAIL $p -> $code"; failures+=("$p -> $code");;
            esac
          done
          if [ "$ok" -eq 0 ]; then
            echo "::error::No endpoint returned success."
            printf '%s\n' "${failures[@]}"; exit 1
          fi
