name: AI — Post-Deploy Smoke
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "ai_probe/**"
      - ".github/workflows/ai-smoke.yml"

jobs:
  smoke:
    environment: staging
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
    env:
      BASE: ${{ secrets.FUNC_BASE_URL }}          # optional
      CODE: ${{ secrets.FUNC_CODE_DEFAULT }}      # optional
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC) — only if CODE not set
        if: env.CODE == ''
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Derive BASE if missing
        if: env.BASE == ''
        run: |
          APP="${{ secrets.AZURE_FUNCTIONAPP_NAME }}"
          if [ -z "$APP" ]; then
            echo "AZURE_FUNCTIONAPP_NAME secret is missing in the staging environment"; exit 1
          fi
          echo "BASE=https://$APP.azurewebsites.net" >> "$GITHUB_ENV"

      - name: Fetch default host key (when CODE is empty)
        if: env.CODE == ''
        run: |
          set -euo pipefail
          APP="${{ secrets.AZURE_FUNCTIONAPP_NAME }}"
          if [ -z "$APP" ]; then
            echo "AZURE_FUNCTIONAPP_NAME is not set in the staging environment secrets"; exit 1
          fi
          RG="$(az functionapp list --query "[?name=='$APP'].resourceGroup" -o tsv)"
          if [ -z "$RG" ]; then
            RG="$(az resource list --name "$APP" --resource-type Microsoft.Web/sites --query [0].resourceGroup -o tsv)"
          fi
          if [ -z "$RG" ]; then
            echo "Could not determine resource group for $APP"; exit 1
          fi
          KEY="$(az functionapp keys list -n "$APP" -g "$RG" --query functionKeys.default -o tsv)"
          if [ -z "$KEY" ]; then
            echo "Could not fetch default host key for $APP in RG $RG"; exit 1
          fi
          # Make CODE available to subsequent steps
          echo "CODE=$KEY" >> "$GITHUB_ENV"

      - name: Show derived settings (safe)
        run: |
          echo "BASE=$BASE"
          echo "CODE set: $([[ -n "$CODE" ]] && echo yes || echo no)"

      - name: Run AI Probe
        run: bash scripts/post_deploy_smoke.sh
