name: AI — Post-Deploy Smoke
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "ai_probe/**"
      - ".github/workflows/ai-smoke.yml"

jobs:
  smoke:
    environment: staging
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
    env:
      BASE: ${{ secrets.FUNC_BASE_URL }}
      CODE: ${{ secrets.FUNC_CODE_DEFAULT }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC) — only if CODE not set
        if: env.CODE == ''
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Fetch default host key (when CODE is empty)
        if: env.CODE == ''
        id: hostkey
        run: |
          set -euo pipefail
          APP="${{ secrets.AZURE_FUNCTIONAPP_NAME }}"
          if [ -z "$APP" ]; then
            echo "AZURE_FUNCTIONAPP_NAME is not set in the staging environment secrets"; exit 1
          fi
          # Robust RG discovery (no -g required)
          RG="$(az functionapp list --query "[?name=='$APP'].resourceGroup" -o tsv)"
          if [ -z "$RG" ]; then
            RG="$(az resource list --name "$APP" --resource-type Microsoft.Web/sites --query [0].resourceGroup -o tsv)"
          fi
          if [ -z "$RG" ]; then
            echo "Could not determine resource group for $APP"; exit 1
          fi
          KEY="$(az functionapp keys list -n "$APP" -g "$RG" --query functionKeys.default -o tsv)"
          if [ -z "$KEY" ]; then
            echo "Could not fetch default host key for $APP in RG $RG"; exit 1
          fi
          echo "code=$KEY" >> "$GITHUB_OUTPUT"

      - name: Run AI Probe
        env:
          BASE: ${{ env.BASE }}
          CODE: ${{ steps.hostkey.outputs.code || env.CODE }}
        run: bash scripts/post_deploy_smoke.sh
