name: DISABLED — Managed by Altus cleanup

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: This workflow is intentionally disabled
        run: |
          echo "This workflow was disabled to prevent duplicate or incorrect deployments."
          echo "Re-enable by restoring the original file from git history or by replacing the triggers under 'on:'."
