name: Deploy Functions — staging

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Ensure Oryx (Kudu) builds requirements.txt into .python_packages on Azure
      - name: Deploy to Azure Functions (staging) with Oryx build
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: .
          scm-do-build-during-deployment: true  # trigger Kudu/oryx build on Azure
          enable-oryx-build: true               # allow oryx to detect Python and install deps
          respect-funcignore: true
          respect-pom-xml: false
          remote-build: false
