name: Deploy Functions App

on:
  push:
    branches: [ main ]
  # Adds the green "Run workflow" button in the Actions tab
  workflow_dispatch:
    inputs:
      deploy_mode:
        description: "Choose deployment method"
        type: choice
        options: [ oidc, publish_profile ]
        default: oidc

permissions:
  id-token: write   # required for OIDC
  contents: read

concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  # ---------------- OIDC (preferred) ----------------
  deploy_oidc:
    if: ${{ github.event_name == 'push' || github.event.inputs.deploy_mode == 'oidc' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (optional local build)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: '.'
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          respect-funcignore: true

  # --------------- Publish Profile (fallback) ---------------
  deploy_publish_profile:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_mode == 'publish_profile' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (optional local build)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure Functions (Publish Profile)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: '.'
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          respect-funcignore: true
