name: Nightly — DB Audit

on:
  schedule:
    - cron: '23 3 * * *'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install psql
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - name: Run verify_all_v2.sql
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          echo "## DB Audit Results" >> $GITHUB_STEP_SUMMARY
          psql "$SUPABASE_DB_URL" -v "ON_ERROR_STOP=1" -c "\! echo '--- Raw vs Normalized (all entities) ---'"
          psql "$SUPABASE_DB_URL" -v "ON_ERROR_STOP=1" -f sql/verify_all_v2.sql | tee audit_output.txt
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Raw Output" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat audit_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
