name: nightly-db-audit

on:
  schedule:
    - cron: '23 3 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clients
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client dnsutils

      - name: Build IPv4 DSN
        id: build
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${SUPABASE_DB_URL:-}" ]; then
            echo "Missing SUPABASE_DB_URL secret" >&2
            exit 1
          fi
          host=$(python3 - <<'PY'
import os, re
dsn=os.environ["SUPABASE_DB_URL"]
m=re.search(r'@([^:/?]+)', dsn)
print(m.group(1) if m else "", end="")
PY
)
          if [ -z "$host" ]; then echo "Could not parse host"; exit 1; fi
          ipv4=$(getent ahostsv4 "$host" | awk '{print $1; exit}') || true
          if [ -z "$ipv4" ]; then ipv4=$(dig +short A "$host" | head -n1); fi
          if [ -z "$ipv4" ]; then echo "Could not resolve IPv4"; exit 1; fi
          if [[ "$SUPABASE_DB_URL" == *\?* ]]; then sep="&"; else sep="?"; fi
          echo "CONN_V4=${SUPABASE_DB_URL}${sep}hostaddr=${ipv4}&sslmode=require&connect_timeout=10" >> $GITHUB_ENV

      - name: Run verify_all_v2.sql (IPv4)
        env:
          CONN_V4: ${{ env.CONN_V4 }}
        run: |
          echo "## DB Audit Results" >> $GITHUB_STEP_SUMMARY
          psql "$CONN_V4"_
