name: Schema Guards

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  verify-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run schema guard (Supabase)
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo 'ERROR: SUPABASE_DB_URL secret is not set'; exit 1;
          fi
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f schema_guard.sql
