name: Schema Sync (HTTP direct commit, safe)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure schema dir
        run: mkdir -p schema

      - name: Export manifest.json via Supabase REST RPC (fail on HTTP error)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${SUPABASE_URL:-}" ] || [ -z "${SUPABASE_SERVICE_ROLE_KEY:-}" ]; then
            echo "::error::Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY repo secrets"; exit 1;
          fi
          if echo "$SUPABASE_URL" | grep -qiE '^postgres(ql)?://'; then
            echo "::error::SUPABASE_URL must be the HTTPS URL (e.g., https://<project>.supabase.co), not the postgres URI."; exit 1;
          fi
          RPC="$SUPABASE_URL/rest/v1/rpc/export_schema_manifest"
          echo "Calling $RPC"
          http_code=$(curl -sS -w "%{http_code}" -o manifest.tmp.json -X POST "$RPC"             -H "apikey: $SUPABASE_SERVICE_ROLE_KEY"             -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY"             -H "Content-Type: application/json"             -d '{"schema_name":"public"}')
          if [ "$http_code" != "200" ]; then
            echo "::error::HTTP $http_code from Supabase RPC"; echo "--- Response body ---"; cat manifest.tmp.json; exit 1;
          fi
          jq '.' manifest.tmp.json > schema/manifest.json
          rm -f manifest.tmp.json

      - name: Commit & push if changed
        run: |
          if git diff --quiet -- schema/manifest.json; then
            echo "No schema changes."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add schema/manifest.json
          git commit -m "chore(schema): sync manifest.json (HTTP direct)"
          git push origin HEAD:main
