name: Schema Sync (HTTP direct commit)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure schema dir
        run: mkdir -p schema

      - name: Export manifest.json via Supabase REST RPC
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_SERVICE_ROLE_KEY" ]; then
            echo "::error::Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY repo secrets"; exit 1;
          fi
          RPC="$SUPABASE_URL/rest/v1/rpc/export_schema_manifest"
          echo "Calling $RPC"
          curl -sS -X POST "$RPC"             -H "apikey: $SUPABASE_SERVICE_ROLE_KEY"             -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY"             -H "Content-Type: application/json"             -d '{"schema_name":"public"}'             | jq '.' > schema/manifest.json

      - name: Commit & push if changed
        run: |
          if git diff --quiet -- schema/manifest.json; then
            echo "No schema changes."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add schema/manifest.json
          git commit -m "chore(schema): sync manifest.json (HTTP direct)"
          git push origin HEAD:main
